# Generated by Django 3.2.19 on 2023-12-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
