# Generated by Django 3.2.19 on 2023-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_chat',
            field=models.BooleanField(default=True),
        ),
    ]
