# Generated by Django 3.2.19 on 2023-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_notification_is_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_chat',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_notifcation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='like_notifcation',
            field=models.BooleanField(default=False),
        ),
    ]
