# Generated by Django 3.2.19 on 2023-12-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20231210_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
