# Generated by Django 3.2.19 on 2023-12-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_notification_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post_id',
        ),
    ]
