# Generated by Django 3.2.19 on 2023-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_notification_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment_notifcation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='like_notifcation',
        ),
    ]
