# Generated by Django 3.2.19 on 2023-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20231210_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
