# Generated by Django 3.2.19 on 2023-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_notification_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='replay_notifcation',
            field=models.BooleanField(default=False),
        ),
    ]
