# Generated by Django 3.2.19 on 2023-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_notification_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow_notifcation',
            field=models.BooleanField(default=False),
        ),
    ]
