# Generated by Django 3.2.19 on 2023-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231021_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_user',
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
