# Generated by Django 3.2.19 on 2023-10-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231025_0313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelOne',
        ),
        migrations.DeleteModel(
            name='ModelTwo',
        ),
    ]
