# Generated by Django 3.2.19 on 2023-10-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_replay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
