# Generated by Django 3.2.19 on 2023-10-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_replay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
