# Generated by Django 3.2.19 on 2023-10-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_status',
            field=models.BooleanField(default=False),
        ),
    ]
