# Generated by Django 3.2.19 on 2023-10-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_like_liked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_status',
            field=models.BooleanField(default=False),
        ),
    ]
