# Generated by Django 3.2.19 on 2023-11-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_block_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='authorprofile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
