# Generated by Django 3.2.19 on 2023-11-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_block_authorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='authorprofile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
