# Generated by Django 3.2.19 on 2023-11-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_block_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blocked_user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user_profile', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='block',
            name='authorprofile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='authorprofile', to='base.profile'),
        ),
    ]
