# Generated by Django 3.2.19 on 2023-11-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20231106_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
