# Generated by Django 3.2.19 on 2023-11-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0023_delete_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_block', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('authorprofile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='authorprofile', to='base.profile')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('blocked_user_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user_profile', to='base.profile')),
            ],
        ),
    ]
