# Generated by Django 3.2.19 on 2023-11-17 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0024_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='following_user',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following_user_profile',
        ),
        migrations.AddField(
            model_name='follow',
            name='following_user_profile',
            field=models.ManyToManyField(related_name='followers_profile', to='base.Profile'),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_id',
        ),
        migrations.AddField(
            model_name='follow',
            name='user_id',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_id_profile',
        ),
        migrations.AddField(
            model_name='follow',
            name='user_id_profile',
            field=models.ManyToManyField(related_name='following_profile', to='base.Profile'),
        ),
    ]
