# Generated by Django 3.2.19 on 2023-11-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20231118_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
