# Generated by Django 3.2.19 on 2023-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
