# Generated by Django 3.2.19 on 2023-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_userloginhistory_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
