# Generated by Django 3.2.19 on 2023-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_userloginhistory_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='status',
            field=models.CharField(default='offline', max_length=100),
        ),
    ]
