# Generated by Django 3.2.19 on 2023-12-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_userloginhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginhistory',
            name='status',
        ),
    ]
