# Generated by Django 3.2.19 on 2024-01-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Image',
            new_name='Image',
        ),
    ]
