# Generated by Django 3.2.19 on 2024-01-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20240102_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
