from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name ='login'),
    path('logout/', views.user_logout, name ='logout'),
    path('signup/', views.signup, name ='signup'),
    path('index/', views.index, name ='index'),
    path('', views.index, name ='index'),
    path('profile/<int:id>/', views.profile, name ='profile'),
    path('blocklist/<int:bid>/', views.blocklist, name ='blocklist'),
    path('suggestion/', views.suggestion, name ='suggestion'),
    path('update/<int:id>/', views.update, name ='update'),
    path('profile_image_update/<int:id>/', views.profile_image_update, name ='profile_image_update'),
    path('name_edit/<int:id>/', views.name_edit, name ='name_edit'),
    path('setting/', views.setting, name ='setting'),
    path('render_/', views.rendertosetting, name ='render_'),
    path('verify/<slug:token>/', views.account_verify, name ='verify'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('postedit/<int:id>/', views.postedit, name='postedit'),
    path('commentedit/<int:id>/', views.commentedit, name='commentedit'),
    path('replayedit/<int:id>/', views.replayedit, name='replayedit'),
    path('postdelete', views.postdelete, name='postdelete'),
    path('profile_post_delete', views.profile_post_delete, name='profile_post_delete'),
    path('comment_delete', views.comment_delete, name='comment_delete'),
    path('replay_delete', views.replay_delete, name='replay_delete'),
    path('comment/<int:id>', views.comment, name='comment'),
    path('comment/show_comment/<int:id>/', views.show_comment, name='show_comment'),
    path('show_replay/<int:pid>/<int:cid>/', views.show_replay, name='show_replay'),
    path('showblocklist/', views.showblocklist, name='showblocklist'),
    path('unblock/<int:block_user_id>/', views.unblock, name='unblock'),
    path('download_image/<int:image_id>/', views.download_image, name='download_image'),
    path('reports/<str:username>/', views.reports, name='reports'),
    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('suggestion_follow_user/<int:user_id>/', views.suggestion_follow_user, name='suggestion_follow_user'),
    path('followers/<int:user_id>/', views.follower_list, name='follower_list'),
    path('following/<int:user_id>/', views.following_list, name='following_list'),
]


